version: '2.1'

services:

  celerophp:
    build: ./php
    ports:
      - "80:80"
    links:
      - celerodb
    container_name: celerophp
    volumes:
      - C:/Users/ma1079898/Desktop/CELERO:/var/www/html
      - ./apache_log:/var/log/apache2

  celerodb:  
    build:
      context: ./db
      args:
        PASSWORD: password
        USER: postgres
    ports:
      - "5432:5432"
    volumes_from:
      - celerodbdata
    container_name: celerodb
    environment:
      POSTGRES_PASSWORD: password

  pgadmin:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8001
    ports: 
          - 8001:8001
    depends_on:
      - celerodb

  #No Linux, only data container
  celerodbdata:  
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - C:/Users/ma1079898/Desktop/celerodb_new:/var/lib/postgresql/data
    container_name: celerodbdata