version: '2.1'

services:

  celerophp-test:
    build: ./php
    ports:
      - "8080:80"
    links:
      - celerodb-test
    container_name: celerophp-test
    volumes:
      - /home/celero/celero-test:/var/www/html
      - ./apache_log:/var/log/apache2
    user: "0:0"

  celerodb-test:  
    build:
      context: ./db
      args:
        PASSWORD: password
        USER: postgres
    ports:
      - "3001:5432"
    volumes_from:
      - celerodbdata-test
    container_name: celerodb-test
    environment:
      POSTGRES_PASSWORD: password
  
  #No Linux, only data container
  celerodbdata-test:  
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /home/celero/celero-test/celerodb:/var/lib/postgresql/data
    container_name: celerodbdata-test