version: '2.1'

services:

  celerophp:
    build: ./php
    ports:
      - "80:80"
      - "443:443"
    links:
      - celerodb
    networks:
      celero:
        ipv4_address: 172.21.0.4
    container_name: celerophp
    volumes:
      - /home/celero/celero-docker:/var/www/html
      - ./apache_log:/var/log/apache2
      - /etc/letsencrypt:/etc/letsencrypt
        #volumes_from:
        #- letsencryptdata
        #user: "33:33"
    restart: always

  celerodb:  
    build:
      context: ./db
      args:
        PASSWORD: password
        USER: postgres
    networks:
      - celero
    ports:
      - "3001:5432"
    volumes_from:
      - celerodbdata
    container_name: celerodb
    environment:
      POSTGRES_PASSWORD: password

      #letsencryptdata:
    #image: cogniteev/echo
    #command: echo 'Data Container for letsencrypt'
    #volumes:
    #  - /var/celero/letsencrypt:/etc/letsencrypt
    #container_name: letsencryptdata
    #restart: always
  
  #No Linux, only data container
  celerodbdata:  
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /home/celero/celero-docker/celerodb:/var/lib/postgresql/data
    container_name: celerodbdata

networks:
  celero:
    external:
      name: celeronet
